### ISSUE TITLE
[Conflict] Crash with MemoryLeakFix

### ISSUE THREAD

**Issue by JustAHuman-xD** [enjarai/shared-resources#4] opened 2022-09-29 05:53 UTC
When starting the game with MemoryLeakFix and Shared resources i get the following crash:

Crash Error:
https://pastebin.com/eeg1f0uH
[Crash.txt](https://github.com/enjarai/shared-resources/files/9671441/Crash.txt)

Full Log:
https://pastebin.com/WNnZs7tB 
[latest.log](https://github.com/enjarai/shared-resources/files/9671438/latest.log)

**Comment by enjarai** [comment] 2022-09-29 08:03
Thats strange... This doesn't happen when you remove MemoryLeakFix?

**Comment by JustAHuman-xD** [comment] 2022-09-29 11:53
Yes it does not happen when I remove memory leak fix

**Comment by enjarai** [comment] 2022-09-29 12:08
Hmmm, I'll look into it. I can't tell from the logs where the conflict might be, but if I recreate it, I might be able to determine the cause.

**Comment by wafflecoffee** [comment] 2022-10-02 14:35
MemoryLeakFix [audits all mixins](https://github.com/fxmorin/MemoryLeakFix/blob/1.19.1/src/main/java/ca/fxco/memoryleakfix/MemoryLeakFix.java#L27-L43). For whatever reason, [RealmsUploadScreenMixin#sharedresources$changePath](https://github.com/enjarai/shared-resources/blob/master/src/main/java/nl/enjarai/shared_resources/common/mixin/saves/RealmsUploadScreenMixin.java#L15-L31) fails this audit, at least on 1.19.2 (I have not tested on other versions), thus crashing the game.

**Comment by enjarai** [comment] 2022-10-02 14:41
Oh, I would never have noticed that, do you have any idea what criteria cause the audit to fail? If not, I'll probably just disable that mixin, since its not very critical to the functioning of the mod at all.

**Comment by wafflecoffee** [comment] 2022-10-02 15:36
You're mixing into the wrong place. The `upload` method almost entirely consists of creating a new thread and then all of the actual code is within that new thread. Thus, the `upload` method actually barely has any code, and instead the code you want is within the synthetic `method_22106`. I'm not entirely sure which `new File` call you want to target, but your mixin is going to want to target `method_22106` instead of `upload`.

**Comment by enjarai** [comment] 2022-10-02 15:49
Oh I see, I totally missed that lambda there and thought the errors were just intellij being funky as always. I'll push out an update to remove that mixin soon, its hard to test anyway since its to do with realms.

**Comment by enjarai** [comment] 2022-10-02 16:05
Fixed in 1.2.1, thanks for the help!

**Closed by enjarai** 2022-10-02 16:05 UTC
